In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [14]:
salary_train = pd.read_csv("SalaryData_Train.csv")
salary_test = pd.read_csv("SalaryData_Test.csv")
string_columns=["workclass","education","maritalstatus","occupation","relationship","race","sex","native"]

In [15]:
from sklearn import preprocessing
number = preprocessing.LabelEncoder()
for i in string_columns:
    salary_train[i] = number.fit_transform(salary_train[i])
    salary_test[i] = number.fit_transform(salary_test[i])

In [16]:
colnames = salary_train.columns
len(colnames[0:13])
trainX = salary_train[colnames[0:13]]
trainY = salary_train[colnames[13]]
testX  = salary_test[colnames[0:13]]
testY  = salary_test[colnames[13]]

In [17]:
sgnb = GaussianNB()
spred_gnb = sgnb.fit(trainX,trainY).predict(testX)
print(spred_gnb)

[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' >50K' ' <=50K']


In [18]:
confusion_matrix(testY,spred_gnb)

array([[10759,   601],
       [ 2491,  1209]], dtype=int64)

In [19]:
print ("Accuracy",(10759+1209)/(10759+601+2491+1209)) 

Accuracy 0.7946879150066402


In [36]:
smnb = MultinomialNB()
spred_mnb = smnb.fit(trainX,trainY).predict(testX)
print(spred_mnb)

[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' >50K' ' <=50K']


In [21]:
confusion_matrix(testY,spred_mnb)

array([[10891,   469],
       [ 2920,   780]], dtype=int64)

In [25]:
print("Accuracy",(10891+780)/(10891+780+2920+469))

Accuracy 0.7749667994687915


In [27]:
sbnb = BernoulliNB(binarize= True)
spred_bnb = sbnb.fit(trainX,trainY).predict(testX)
print(spred_bnb)

[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' <=50K' ' <=50K']


In [28]:
confusion_matrix(testY,spred_bnb)

array([[10897,   463],
       [ 2772,   928]], dtype=int64)

In [29]:
print("Accuracy",(10897+928)/(10897+463+2772+928))

Accuracy 0.7851925630810093
